INSERT INTO cards (question, answer, deck_id) VALUES ("A, An","Without: amoral, anarchy, anomalous, anonymous, aseptic, asexual, atheism, atrophy, averse",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ab","From Away Apart: abdicate, abduct, abhor, abject, abnormal, abrupt, absent, abuse",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Able, Ible","Capable of, Worthy Of: changeable, durable, laudable, indubitable, inevitable, infalible, irreducible, tolerable, variable",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ac, Acr","Sharp, Sour: acerbic, acetate, acid, acrid, acrimony, acumen, acute",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Acou","Hearing: acoustic",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ad, A","To: adapt, adequate, adumbrate, advocate, accede, adduce, affiliate, aggregate, allocate, annuniciation, appall, arrest, assiduous, attract",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ambi, Amphi","Both, On Both Sides, Around: ambidextrous, ambient, ambiguous, ambition, ambivalent, amphibian, amphitheater",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ambl, Ambul","Walk: amble, ambulance, ambulatory, perambulator, preamble",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Anim","Mind, Spirit, Breath: animadversion, animal, animate, animosity, equanimity, magnanimity, pusillanimous, unanimity",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ant, Ante","Before: antecedent, antechamber, antediluvian, anterior, anticipate, antiquity, ancient",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Anti, Ant","against, oppostite: anticlimax, antidote, antipathy, anitphony, antipodes, antithesis",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Aqua, Aque","Water: aquamarine, aquarium, aquatic, aquatint, aqueduct, subaqueous",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ard","Burn: ardent, ardor, arson",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Auto, Aut","Self: autobiography, autocracy, autograph, automation, autonomous, autopsy, autism",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Bel, Bell","War: antebellum, bellicose, belligerent, rebellion",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ben","Well, Good: benediction, benefactor, benevolent, benign",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Bi, Bin","Two: bicameral, bicycle, bifocals, bifurcate, bilateral, binoculars, binomial, biped, combination",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Bon, Boun","Good, Generous: bonus, bountiful, bounty, debonair",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Brew, Brid","Short, Small: abbreviate, abridge, brevet, breviary, breviary, breviloquent, brief",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Burs","Purse, Money: busary, busary, disburse, reimburse",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cap, Cipt, Capt, Cept","Hold, Take:   capture, captive, conception, recipient",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Carn","Flesh: Carnivorous, incarnate, reincarnation, carnal",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Caus, Caut","Burn: caustic, cauterize, cautery, encaustic, holocaust",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ced, Cess","Yield, Go: abscess, accede, access, accessory, ancestory, antecedent, cession, concede, exceed, excess, intercede, precede, proceed, recede, recess, recession, secede, succeed",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Celer","Speed: accelerate, celerity, deccelerate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cent","Hundred, Hundredth: cent, centennial, bicentennial, centigrade, centigram, centiliter, centimeter, centipede, century, percent",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Chrom","Color: chromatic, chrome, chromosome, monochromatic",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Chron","Time: anachronism, chronic, chronicle, chronological, chronometer, synchronize",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Circum","Around: circumference, circumlocation, circumnavigate, circumspect, circumstance",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Co, Com, Con","With Together: coeductation, coefficient, coincide, communicate, communist, compare, concert, concubine, conflict, cooperate, correspond",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Contra, Contro","Against: contradict, contrary, controversy, counter, counteract, counterattack, counterfeit, countermand, counterpart, counterpoint, eencounter",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cord, Card","Heart: accord, cardiac, cardiograph, cardiology, concord, cordial, discord, record",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Corp, Cors","Body: corporate, corps, corpse, corpulent, corpus, corpuscle, corset, incorporation",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cosm","Order Universe, World: cosmetic, cosmic, cosmology, cosmonaut, cosmopolitan, cosmos, microcosm",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cred","Trust, Believe: accredit, credentials, credible, creditable, credo, credulity, creed, incredible, incredulous",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Crypt","Hide: crypt, cryptic, crytography, apocryphal",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Culp","Fault, Blame: culpable, culprit, inculpate, exculpate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cumb, Cub","Lie Down: concubine, cubicle, incubate, incumbent, recumbent, succubus, succumb",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cyn, Can","Dog: canine, cynic",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("De","Down, Out, Away From, Apart: dehydrate, deject, depend, depress, deport, descend, describe, devalue",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dele","Erase: dele, delete, indelible",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dext","Right Hand, Rightside: ambidextrous, dexterity, dexterous",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Di","Day: dial, diary, dismal, diurnal, meridian, quotidian",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dia","Through, Across: diadem, diagnosis, diagonoal, diagram, dialect, dialogue, diameter, diaphanous, diaphragm, diarrhea, diatribe",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dic, Dict, Dit","Speak: abdicate, addict, benediction, condition, contradict, dedicate, dictate, dietator",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Di, Dis","Away, Apart: disagreeable, discard, discern, disdain, dismay, dismiss, distant, diverge",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dol","Grieve: condole, condolence, doleful, dolor, indolent",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dorm","Sleep: dormant, dormitory",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dors","Back: dorsal, endorse",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Duc, Duct","Lead: adduce, conduce, conduit, deduce, duct, duke, educate, induction, misconduct, produce, reduce, seduce, traduce, viaduct",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dulc","Sweet: dulcet, dulcified, dulcimer",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dur","Hard, Lasting: dour, durable, duration, duress, during, endure, obdurate, perdurable",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ei, Ex, Ex","without, outside: eliminate, emanate, eradicate, erase, evade, evit, envince, exact, excavate, except, excerpt, excite, exclusive, excommunicate, excrescence, execute, exhale, exile, exit",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ego","Self: ego, egocentric, egoism, egotist",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Equ","Equal: adequate, equable, equal, equation, equator, equilibrium, equinox, rquivocate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Err","Wander: aberration, err, errant, erratic, erroneous, error",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Eu","Well, Good: Eugenics, eulogy, euphemism, euphony, euphoria, euthanasia",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fal","Liable to Err to Deceive: default, fail, fallacy, false, faux, pas, infallible",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fatu","Foolish: fatuity, fatuous, infatuate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ferv","Boil: effervescent, fervent, fervid, fervor",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fid, Fi","Fair, Faith: affiance, affidavit, confidant, fidelity, fiducial, fiduciary",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Flagr, Fulg, Fulm","Burn, Shine: conflagration, effulgent, flagrant, fulgent, fulminate, refulgent",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Flect, Flex","Bend, Turn: circumflex, deflect, flex, flexible, inflection, reflect",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fug","Flee: centrifuge, fugitive, refuge, refugee, subterfuge",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fur","Steal:  furtive",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fum","Smoke: fume, fumigate, perfume",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Gen","Birth, Class, Kin: gender, gende, general, generation, generosity, genesis, genetics, genial, genital, genius, gentle, gentile, gentility, gentry, congenital, degenerate, eugenics, ingenious, ingenuity, ingenuous, progeny, progenitor, regenerate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("GNO, GNI, COGN","Know: agnostic, cognition, cognizance, diagnosis, gnomic, ignore, incognito, prognosis, quaint, recognize, reconnaissance",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Gram, Graph","Write, Draw: anagram, diagram, epigram, grammar, grammarian, gramphone, graph, graphic, graphite, phography, photograph, program, telegram",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Greg","Flock: aggregate, congregate, egregious, gregarious, segregate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Hap","By Chance: haphazard, hapless, happen, happily, happy, mahap, mishap",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Hemi","Half: hemiptera, hemipshere, hemistih",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Hetero","Other: heterodox, heterodyne, heterogeneous, heterosexual",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Hol","Whole: catholic, holocaust, hologram, holgraphy, holistic",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Homo","Same (from greek): Homogeneous, homogenize, homologue, homonym, homophone, homoptera, homsexual, homotype",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Hum","Earth: exhume, humility, psthumous",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Icon","Image, Idol: icon, iconic, iconoclast, iconography, iconology",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("IM, IN","Not: immature, immutable, imperfect, improvident, indigestible, inhospitable, innocuous, intolerant",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("In, IM, I","In, On: illuminate, incantation, induct, infer, imbibe, immigrate, impact, irrigate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Inter","Between, Among: intercept, intrastate, intravenous",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("IT, ITER","Way, Journey: ambition, circuit, initial, itinerant, itinerary, reiterate, transit",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Joc","Joke: jocose, jocular, jocularity, jocund, joke",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Jour","Day: adjourn, journey, journal, adjourn",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Jud","Judge: adjudicate, judiciary, judicious, prejudice",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Junct, Jug","Join: adjunct, conjugal, conjunction, injunction, junction, subjugate, subjunctive",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Jur","Law: abjure, adjure, conjure, juridical, jurisdiction, jurisprudence, juristy, jurty, perjury",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Juv","Young: juvenile, juvenilia, rejuvenate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Laud","Praise: applaud, cum laude, laud, laudable, laudatory, plaudits",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lav, Lau, Lu","Wash: ablution, laundry, lava, lavatory",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lax, Lak, Leas, L","Loose: lax, laxative, laxity, lease, leash, lessee, lessor, relax, release",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Leg, Lec, Lex","Read, Speak: dialect, lectern, leture, legend, legible, lesson, lexicographer, lexicon",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lev","Light: alleviation, elevate, leaven, lever, levitate, levity, levy, relieve",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Liber","Free: delivery, illiberal, liberal, liberality, liberate, libertine",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lig, Li","Tie, Bind: ally, league, liaison, liable, lien, ligament, ligature, oblige, religion, rely",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ling, Lang","Tongue: bilingual, language, linguistics",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lith","Stone: acrolith, lithography, lithoid, lithology, lithotomy, megalith, monolith",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Log, Loqu","Speech, Thought: biology, circumlocution, colloquial, dialogue, ecology, elocution, eloquent, geology, gradiloquent, interlocutor, locution, logic, loquacious, monoloque, obloquy, soliloquy, ventriloquism, zoology",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lux, Luc","Light: elucidate, luid, lucubrate, luster, pellucid, translucent",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Macro","Great, Long: macrobiotics, macrocephalous, macrocosm",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mag, Max, Maj, Ma","Great: magistrate, maganimous, magnate, magnificent, magnify, magniloquent, magnitude, majesty, major, majority, master, maxim, maximum, mistress",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mal","Bad: maladroit, malady, malediction, malefactor, malevolence, malice, malinger",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Man, Manu","Hand: amanuensis, manacle, manage, maneuver, manifest, manipulate, manner, manual, manufacture, manuscript",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mand, Mend","Command, Order: command, countermand, demand, mandate, mandatory, recommend, remand, reprimand",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Medi","Middle: immediate, intermediate, mean, media, median, mediate, medieval, mediocre, medium, medius",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mega","Large, Great: megalithic, megalomania, megalopolis, megaphone, megaton",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Micro","Very Small: microbe, micrcosm, micron, microorganism, microphone, microscope",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mis","Bad, Wrong, Hate: misadventure, misanthropist, misapply, miscarry, mischance, mischeif, misconstrue, miscount, misfit, misinterpret",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Moll","Soft: emmollient, mild, mollify, mollusk",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mon, Mono","One: monarchy, monastic, monism, monk, monochord, monograph, monogram, mongraph, monolithic, monolgue, monomania, monosyllable, monotonous",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mor, Mort","Death: amortize, immortal, morbid, moribund, mortality, mortgage, mortification, mortuary",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mot, Mov, Mom, Mo","Move: automobile, demote, immovable, locomotion, mob, mobile, mobility, mobilize, momentous, momentum, motion, motive, motor, move, mutiny, promote, removable",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mult","Many: multiplex, multiply, multitudinous",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mut","Change: commute, immutable, mutability, mutation, mutual, permutation, transmute",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nasc, Nat, GNA","Birth: cognate, innate, nascent, natal, native, natural, nature, pregnant, Renaissance",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nau, Nav","Ship, Sailor: astronaut, cosmonaut, circumnavigate, nauseous, nautical, naval, nave, navy",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Neo","New: neolithic, neologism, neophyte, neoplasm",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nihil","Nothing, None: annihilate, nihilism",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Noct, Nox","Night: equinox, noctambulent, nocturnal, nocturne",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nox, Noc","Harm: innocent, innocuous, internecine, nocious, nuisance, obnoxious, pernicious",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nom, Nym, Nec","Name: anonymous, antonym, cognomen, denominator, homony,. misnomer, nomenclature, nominal, nominate, noun, pronoun, pseudonym, renowned, synonym",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Non","Not: nonconformist, nonentity, nonpareil, nonpartisan",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nov","New: innovate, nova, novel, novelty, novice, novitiate, renovate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Null","Nothing: annul, null, nullify, nulity",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ob","Against: obdurate, obliterate, oblong, obloquy, object, obstacle, obstreperous, obstruct",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Omni","All: omnibus, omnipresent, omnipotent, omniscient, omnivorous",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Oner","Burden: exonerate, onerous, onus",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Oss, Oste","Bone: osseous, ossicle, ossiferous, ossify, ossuary, osstectomy, ostepathy",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Palp","Feel: palpable, palpate, palitation",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pan, Pant","All: panacea, pandemic, panoply, panorama, pantheon, pantomine",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Path","Suffer, Feel: apathy, antipathy, empathy, pathetic, pathology, pathos, sympathy",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pec","Money: impecunious, peculation, pecuniary",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pot","Drink: potable, potation, potion",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pre","Before, In Front: preamble, precaution, preclude, precocity, precursor, predecessor, predict, preface, prefigure, prelate, premonition, presrcie, president",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Prim, Pri","First: prime, primary, primal, primeval, primordial, pristine",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pro","In Front, Before: problem, proboscis, procedure, proceed, proclaim, prodivity, proscrastinate, procure, propound, prostrate, protest",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Prop, Prox","near: approximate, propinquity, proximate, proximity",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Proto, Prot","First: protagonist, protocol, prototype, protozoan",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pseudo, Psed","False: pseudepigrapha, pseudoclassic, pseudomorph, pseudonym, pseudopod, pseduoscientific",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pug, Pun","Hit, Prick: expunge, impugn, poignant, pugilist, pugnacious, punch punctual, punctuate, pungent repugnant",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pyr","Fire: pyre, pyromania, pyrometer, pyrosis, pyrotechnic",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Qua, Quar, Quat","Four: quadrant quadrille, quadrinomial, quadruple, quadruplets, quart, quarter, quaternary",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Quie, Quit","Quiet, Test: acquiesce, acquit, coy, disuiet, quiescent, quiet, quietude, quietus, quit, reguiem, requital, tranquil",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Quint, Quin","Five: quincunx, quinquennial, quintessence, quintile, quintillion, quintuple",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Radi, Raci, Rami","Root, Branch: deracinate, eradicate, radical, radish, ramification, ramiform, ramify",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Re","Back, Again: recline, refer, regain, remain, reorganize, repent, request",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Rect","Straight, Right: correct, direct, erect, rectangle, rectify, rectilinear, rectitude, rector",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Retro","Backword: retroactive, retroflex, retrograde, retrospective",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Rub, Rud","Red: rouge, rebella, rubicund, rubric, ruby, ruddy, russet",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Rud","Crude: euridite, rude, rudimentary, rudiments",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sacer, Sacr, Sanc","Holy: onsecration, desecrate, execrate, sacerdotal, sacrament, sacred, sacrifince, sacrilige, sacristy, sacrosanct, saint, santify, sanctimonious, sanction, sanctity, sancturary, sanctum",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sal","Salt: salary, saline",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sag, Sap, Sav","Taste, Think: insipid, sagacious, sagacity, sage, sapid, sapient, savant, savor",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Salu, Salv","Halth, Save: safe, salubrious, salutary, salute, salvage, salvation, salve, savior",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("San","Healthy: sane, sanitarium, sanitation, sanity",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sang","Blood: consanguinity, sanguinary, sanguine",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sat","Enough: asset, dissatisfied, insatiable, sate, satiate, satisfy, saturate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Scrib, Scriv, Scr","Write: Ascribe, circumscription, conscript, describe, indescribable, inscription, posticript, prescribe, proscribe, scribble, scribe, script, scripture, scrivener, subscribe, transcription",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Se","Down, out, away, Apart: secede, seclude, secrete, secrete, secure, sedition, seduce, segregate, select, separate.",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sed, Sid","Sit: assiduous, dissident, insidious, preside, reside, residue, seance, sedate, sedative, sedentary, sediment, sedulous, session, siege, subside, supersede",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sem","Seed, Sow: disseminate, semen, seminal, seminar, seminary",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Semi","Half: semicircle, semicolon, semiconscious, semifluid",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sen","Old: senate, senescent, senile, seniour, sire",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sequ, Secu, Sue, ","Follow: consecutive, consequent, execute, exutive, non sequitur, obsequious, obsequy, persecute, prosecution, pursue, sequal,sequence, subsequent, sue, suitable, suite, suitor",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sinu, Sin","Bend, Fold: consine, insuinuate, sine, sinuous, sinus",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sol","Sun: parasol, solar, solarium, solstice",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sol","Alone: desolate, isolate, sole, soliloquize, solipsism, solitude, solo",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Somn","Sleep: insomnia, somnambulist, somniferous, somniloquist, somnolent",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Soph","Wisom: philospher, sophism, sophist, sophistry, sophomore",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Spec, Spic","Look, See: aspeect, auspicious, circumspect, conspicious, despicable, expect, inspect, introspection, perspective, persicacious, perspicauous, prospectus, respectable, restrospect, specimen, spectacle, spectator, specter, spectrum, suspect, suspicious",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Spir","Breath: apire, conspire, expire, inspire, perspire, respirator, spirity, spiritual, sprightly, sprite, suspire, transpire",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Strict, String","Tight: astringency, constrain, constrict, district, resstriction, strain, strait, strangle, strict, stringent",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sub","Under: subdivide, subdue, subjugate, subjunctive, sublunary, submarine, submerge, subdordinate, subpoena, subscribe, subside, substitude, subterfuge, subterranean, suburb",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Summ","Highest: consummate, sum, summary, summit",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Super, Sur","Above: insuperable, superabound, superannuated, superb, supercharge, supercilious, superficial, superflous, superior, surpass, surrealism, survey",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Surg, Sourc, Surr","Rise: insurgent, insurrection, resource, resurge, resurrection, source, surge",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sym, Syn","Together: symbiosis, symmetry, sympathy, symposium, synonym, synthesis",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tacit","Silent: reticent, tacit, taciturn",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tact, Tag, Tam, T","Touch: contact, contagious, contamination, contiguous, contangent, intact, intangible, integral, tact, tactile, tangent, tangential",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Test","bear witness: attest, contest, detest, intestate, protest, testament, testify, testimonial",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Therm","Heat: diathermy, thermal, thermesthesia, thermometer, thermonuclear, thermophilic, thermos, thermoststat",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tim","Fear: intimidate, timid, timidity, timorous",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Topr","Stiff, Numb: torpedo, torpid, torpor",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Torq, Tort, Tor","Twist: contort, distort, extor, retor, torch, torment, torque, torsion, tort, tortuous, torture",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tox","Poison: antitoxin, intoxication, toxemia, toxis, tocicology, toxin",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Trans","Across Beyond: intransigent, transcend, transcontinental, transcribe, transient, trasnmit, transpire, transport",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ult","Last, Beyond: penultimate, ulterior, ultimate, ultimatum, ultramarine, ultramontane, ultraviolet",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Umbr","Shadow: adumbrate, penumbra, somber, umber, umbrage, umbrella",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Un","Not: unaccustomed, unruly, unseen, untold, unusual",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Und","Wave: abound, abdundance, unundate, redundant, undulant, undulate",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Uni, Un","One: reunion, unanimous, unicord, uniform, union, unison, unit, unite, unity, universe",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Urb","City: exurbanite, suburban, urban, urbanity, urbanization",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Val, Vail","Strength, Use, Worth: ambivalent, avail, convalescent, countervailing, equivalent, evaluate, invalid, prevalent, valediction, valiant, valid, valor, value",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ver","True: aver, veracious, verdict, verify, verily, verisimilitude, verity, verty",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Verb","Word: adverb, proverb, verb, verbal, verbalize, verbatime, verboze, verbiage",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Verd","Green: verdant, verdigris, verdure",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vil","Base, Mean: revile, vile, vilify, vilification",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vit, Viv","Life: convivial, revival, revive, survive, vital, vitality, vivacious, vivid, viviparous, vivisection",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Voc, Vou","Call, Word: advocacy, advocate, avow, convocation, convoke, equivoval, evoke, invocation, invoke, provoke, revoke, vocabulary, vocal, vocation",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vol","Fly: volant, volatile, volley",6);
INSERT INTO cards (question, answer, deck_id) VALUES ("Volu, Volv","Roll, Tur: circumvolve, convolution, devolve, evolve, involution, revolt, revolve, voluble, colume, vouminous, volute.",6);
