INSERT INTO cards (card_order, question, answer, deck_id) VALUES (1,"A, An","Without: amoral, anarchy, anomalous, anonymous, aseptic, asexual, atheism, atrophy, averse",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (2,"Ab","From Away Apart: abdicate, abduct, abhor, abject, abnormal, abrupt, absent, abuse",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (3,"Able, Ible","Capable of, Worthy Of: changeable, durable, laudable, indubitable, inevitable, infalible, irreducible, tolerable, variable",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (4,"Ac, Acr","Sharp, Sour: acerbic, acetate, acid, acrid, acrimony, acumen, acute",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (5,"Acou","Hearing: acoustic",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (6,"Ad, A","To: adapt, adequate, adumbrate, advocate, accede, adduce, affiliate, aggregate, allocate, annuniciation, appall, arrest, assiduous, attract",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (7,"Ambi, Amphi","Both, On Both Sides, Around: ambidextrous, ambient, ambiguous, ambition, ambivalent, amphibian, amphitheater",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (8,"Ambl, Ambul","Walk: amble, ambulance, ambulatory, perambulator, preamble",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (9,"Anim","Mind, Spirit, Breath: animadversion, animal, animate, animosity, equanimity, magnanimity, pusillanimous, unanimity",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (10,"Ant, Ante","Before: antecedent, antechamber, antediluvian, anterior, anticipate, antiquity, ancient",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (11,"Anti, Ant","against, oppostite: anticlimax, antidote, antipathy, anitphony, antipodes, antithesis",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (12,"Aqua, Aque","Water: aquamarine, aquarium, aquatic, aquatint, aqueduct, subaqueous",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (13,"Ard","Burn: ardent, ardor, arson",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (14,"Auto, Aut","Self: autobiography, autocracy, autograph, automation, autonomous, autopsy, autism",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (15,"Bel, Bell","War: antebellum, bellicose, belligerent, rebellion",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (16,"Ben","Well, Good: benediction, benefactor, benevolent, benign",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (17,"Bi, Bin","Two: bicameral, bicycle, bifocals, bifurcate, bilateral, binoculars, binomial, biped, combination",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (18,"Bon, Boun","Good, Generous: bonus, bountiful, bounty, debonair",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (19,"Brew, Brid","Short, Small: abbreviate, abridge, brevet, breviary, breviary, breviloquent, brief",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (20,"Burs","Purse, Money: busary, busary, disburse, reimburse",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (21,"Cap, Cipt, Capt, Cept","Hold, Take:   capture, captive, conception, recipient",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (22,"Carn","Flesh: Carnivorous, incarnate, reincarnation, carnal",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (23,"Caus, Caut","Burn: caustic, cauterize, cautery, encaustic, holocaust",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (24,"Ced, Cess","Yield, Go: abscess, accede, access, accessory, ancestory, antecedent, cession, concede, exceed, excess, intercede, precede, proceed, recede, recess, recession, secede, succeed",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (25,"Celer","Speed: accelerate, celerity, deccelerate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (26,"Cent","Hundred, Hundredth: cent, centennial, bicentennial, centigrade, centigram, centiliter, centimeter, centipede, century, percent",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (27,"Chrom","Color: chromatic, chrome, chromosome, monochromatic",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (28,"Chron","Time: anachronism, chronic, chronicle, chronological, chronometer, synchronize",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (29,"Circum","Around: circumference, circumlocation, circumnavigate, circumspect, circumstance",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (30,"Co, Com, Con","With Together: coeductation, coefficient, coincide, communicate, communist, compare, concert, concubine, conflict, cooperate, correspond",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (31,"Contra, Contro","Against: contradict, contrary, controversy, counter, counteract, counterattack, counterfeit, countermand, counterpart, counterpoint, eencounter",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (32,"Cord, Card","Heart: accord, cardiac, cardiograph, cardiology, concord, cordial, discord, record",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (33,"Corp, Cors","Body: corporate, corps, corpse, corpulent, corpus, corpuscle, corset, incorporation",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (34,"Cosm","Order Universe, World: cosmetic, cosmic, cosmology, cosmonaut, cosmopolitan, cosmos, microcosm",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (35,"Cred","Trust, Believe: accredit, credentials, credible, creditable, credo, credulity, creed, incredible, incredulous",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (36,"Crypt","Hide: crypt, cryptic, crytography, apocryphal",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (37,"Culp","Fault, Blame: culpable, culprit, inculpate, exculpate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (38,"Cumb, Cub","Lie Down: concubine, cubicle, incubate, incumbent, recumbent, succubus, succumb",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (39,"Cyn, Can","Dog: canine, cynic",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (40,"De","Down, Out, Away From, Apart: dehydrate, deject, depend, depress, deport, descend, describe, devalue",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (41,"Dele","Erase: dele, delete, indelible",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (42,"Dext","Right Hand, Rightside: ambidextrous, dexterity, dexterous",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (43,"Di","Day: dial, diary, dismal, diurnal, meridian, quotidian",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (44,"Dia","Through, Across: diadem, diagnosis, diagonoal, diagram, dialect, dialogue, diameter, diaphanous, diaphragm, diarrhea, diatribe",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (45,"Dic, Dict, Dit","Speak: abdicate, addict, benediction, condition, contradict, dedicate, dictate, dietator",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (46,"Di, Dis","Away, Apart: disagreeable, discard, discern, disdain, dismay, dismiss, distant, diverge",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (47,"Dol","Grieve: condole, condolence, doleful, dolor, indolent",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (48,"Dorm","Sleep: dormant, dormitory",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (49,"Dors","Back: dorsal, endorse",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (50,"Duc, Duct","Lead: adduce, conduce, conduit, deduce, duct, duke, educate, induction, misconduct, produce, reduce, seduce, traduce, viaduct",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (51,"Dulc","Sweet: dulcet, dulcified, dulcimer",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (52,"Dur","Hard, Lasting: dour, durable, duration, duress, during, endure, obdurate, perdurable",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (53,"Ei, Ex, Ex","without, outside: eliminate, emanate, eradicate, erase, evade, evit, envince, exact, excavate, except, excerpt, excite, exclusive, excommunicate, excrescence, execute, exhale, exile, exit",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (54,"Ego","Self: ego, egocentric, egoism, egotist",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (55,"Equ","Equal: adequate, equable, equal, equation, equator, equilibrium, equinox, rquivocate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (56,"Err","Wander: aberration, err, errant, erratic, erroneous, error",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (57,"Eu","Well, Good: Eugenics, eulogy, euphemism, euphony, euphoria, euthanasia",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (58,"Fal","Liable to Err to Deceive: default, fail, fallacy, false, faux, pas, infallible",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (59,"Fatu","Foolish: fatuity, fatuous, infatuate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (60,"Ferv","Boil: effervescent, fervent, fervid, fervor",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (61,"Fid, Fi","Fair, Faith: affiance, affidavit, confidant, fidelity, fiducial, fiduciary",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (62,"Flagr, Fulg, Fulm","Burn, Shine: conflagration, effulgent, flagrant, fulgent, fulminate, refulgent",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (63,"Flect, Flex","Bend, Turn: circumflex, deflect, flex, flexible, inflection, reflect",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (64,"Fug","Flee: centrifuge, fugitive, refuge, refugee, subterfuge",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (65,"Fur","Steal:  furtive",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (66,"Fum","Smoke: fume, fumigate, perfume",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (67,"Gen","Birth, Class, Kin: gender, gende, general, generation, generosity, genesis, genetics, genial, genital, genius, gentle, gentile, gentility, gentry, congenital, degenerate, eugenics, ingenious, ingenuity, ingenuous, progeny, progenitor, regenerate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (68,"GNO, GNI, COGN","Know: agnostic, cognition, cognizance, diagnosis, gnomic, ignore, incognito, prognosis, quaint, recognize, reconnaissance",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (69,"Gram, Graph","Write, Draw: anagram, diagram, epigram, grammar, grammarian, gramphone, graph, graphic, graphite, phography, photograph, program, telegram",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (70,"Greg","Flock: aggregate, congregate, egregious, gregarious, segregate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (71,"Hap","By Chance: haphazard, hapless, happen, happily, happy, mahap, mishap",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (72,"Hemi","Half: hemiptera, hemipshere, hemistih",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (73,"Hetero","Other: heterodox, heterodyne, heterogeneous, heterosexual",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (74,"Hol","Whole: catholic, holocaust, hologram, holgraphy, holistic",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (75,"Homo","Same (from greek): Homogeneous, homogenize, homologue, homonym, homophone, homoptera, homsexual, homotype",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (76,"Hum","Earth: exhume, humility, psthumous",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (77,"Icon","Image, Idol: icon, iconic, iconoclast, iconography, iconology",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (78,"IM, IN","Not: immature, immutable, imperfect, improvident, indigestible, inhospitable, innocuous, intolerant",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (79,"In, IM, I","In, On: illuminate, incantation, induct, infer, imbibe, immigrate, impact, irrigate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (80,"Inter","Between, Among: intercept, intrastate, intravenous",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (81,"IT, ITER","Way, Journey: ambition, circuit, initial, itinerant, itinerary, reiterate, transit",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (82,"Joc","Joke: jocose, jocular, jocularity, jocund, joke",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (83,"Jour","Day: adjourn, journey, journal, adjourn",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (84,"Jud","Judge: adjudicate, judiciary, judicious, prejudice",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (85,"Junct, Jug","Join: adjunct, conjugal, conjunction, injunction, junction, subjugate, subjunctive",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (86,"Jur","Law: abjure, adjure, conjure, juridical, jurisdiction, jurisprudence, juristy, jurty, perjury",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (87,"Juv","Young: juvenile, juvenilia, rejuvenate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (88,"Laud","Praise: applaud, cum laude, laud, laudable, laudatory, plaudits",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (89,"Lav, Lau, Lu","Wash: ablution, laundry, lava, lavatory",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (90,"Lax, Lak, Leas, L","Loose: lax, laxative, laxity, lease, leash, lessee, lessor, relax, release",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (91,"Leg, Lec, Lex","Read, Speak: dialect, lectern, leture, legend, legible, lesson, lexicographer, lexicon",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (92,"Lev","Light: alleviation, elevate, leaven, lever, levitate, levity, levy, relieve",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (93,"Liber","Free: delivery, illiberal, liberal, liberality, liberate, libertine",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (94,"Lig, Li","Tie, Bind: ally, league, liaison, liable, lien, ligament, ligature, oblige, religion, rely",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (95,"Ling, Lang","Tongue: bilingual, language, linguistics",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (96,"Lith","Stone: acrolith, lithography, lithoid, lithology, lithotomy, megalith, monolith",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (97,"Log, Loqu","Speech, Thought: biology, circumlocution, colloquial, dialogue, ecology, elocution, eloquent, geology, gradiloquent, interlocutor, locution, logic, loquacious, monoloque, obloquy, soliloquy, ventriloquism, zoology",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (98,"Lux, Luc","Light: elucidate, luid, lucubrate, luster, pellucid, translucent",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (99,"Macro","Great, Long: macrobiotics, macrocephalous, macrocosm",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (100,"Mag, Max, Maj, Ma","Great: magistrate, maganimous, magnate, magnificent, magnify, magniloquent, magnitude, majesty, major, majority, master, maxim, maximum, mistress",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (101,"Mal","Bad: maladroit, malady, malediction, malefactor, malevolence, malice, malinger",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (102,"Man, Manu","Hand: amanuensis, manacle, manage, maneuver, manifest, manipulate, manner, manual, manufacture, manuscript",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (103,"Mand, Mend","Command, Order: command, countermand, demand, mandate, mandatory, recommend, remand, reprimand",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (104,"Medi","Middle: immediate, intermediate, mean, media, median, mediate, medieval, mediocre, medium, medius",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (105,"Mega","Large, Great: megalithic, megalomania, megalopolis, megaphone, megaton",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (106,"Micro","Very Small: microbe, micrcosm, micron, microorganism, microphone, microscope",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (107,"Mis","Bad, Wrong, Hate: misadventure, misanthropist, misapply, miscarry, mischance, mischeif, misconstrue, miscount, misfit, misinterpret",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (108,"Moll","Soft: emmollient, mild, mollify, mollusk",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (109,"Mon, Mono","One: monarchy, monastic, monism, monk, monochord, monograph, monogram, mongraph, monolithic, monolgue, monomania, monosyllable, monotonous",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (110,"Mor, Mort","Death: amortize, immortal, morbid, moribund, mortality, mortgage, mortification, mortuary",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (111,"Mot, Mov, Mom, Mo","Move: automobile, demote, immovable, locomotion, mob, mobile, mobility, mobilize, momentous, momentum, motion, motive, motor, move, mutiny, promote, removable",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (112,"Mult","Many: multiplex, multiply, multitudinous",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (113,"Mut","Change: commute, immutable, mutability, mutation, mutual, permutation, transmute",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (114,"Nasc, Nat, GNA","Birth: cognate, innate, nascent, natal, native, natural, nature, pregnant, Renaissance",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (115,"Nau, Nav","Ship, Sailor: astronaut, cosmonaut, circumnavigate, nauseous, nautical, naval, nave, navy",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (116,"Neo","New: neolithic, neologism, neophyte, neoplasm",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (117,"Nihil","Nothing, None: annihilate, nihilism",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (118,"Noct, Nox","Night: equinox, noctambulent, nocturnal, nocturne",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (119,"Nox, Noc","Harm: innocent, innocuous, internecine, nocious, nuisance, obnoxious, pernicious",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (120,"Nom, Nym, Nec","Name: anonymous, antonym, cognomen, denominator, homony,. misnomer, nomenclature, nominal, nominate, noun, pronoun, pseudonym, renowned, synonym",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (121,"Non","Not: nonconformist, nonentity, nonpareil, nonpartisan",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (122,"Nov","New: innovate, nova, novel, novelty, novice, novitiate, renovate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (123,"Null","Nothing: annul, null, nullify, nulity",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (124,"Ob","Against: obdurate, obliterate, oblong, obloquy, object, obstacle, obstreperous, obstruct",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (125,"Omni","All: omnibus, omnipresent, omnipotent, omniscient, omnivorous",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (126,"Oner","Burden: exonerate, onerous, onus",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (127,"Oss, Oste","Bone: osseous, ossicle, ossiferous, ossify, ossuary, osstectomy, ostepathy",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (128,"Palp","Feel: palpable, palpate, palitation",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (129,"Pan, Pant","All: panacea, pandemic, panoply, panorama, pantheon, pantomine",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (130,"Path","Suffer, Feel: apathy, antipathy, empathy, pathetic, pathology, pathos, sympathy",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (131,"Pec","Money: impecunious, peculation, pecuniary",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (132,"Pot","Drink: potable, potation, potion",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (133,"Pre","Before, In Front: preamble, precaution, preclude, precocity, precursor, predecessor, predict, preface, prefigure, prelate, premonition, presrcie, president",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (134,"Prim, Pri","First: prime, primary, primal, primeval, primordial, pristine",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (135,"Pro","In Front, Before: problem, proboscis, procedure, proceed, proclaim, prodivity, proscrastinate, procure, propound, prostrate, protest",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (136,"Prop, Prox","near: approximate, propinquity, proximate, proximity",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (137,"Proto, Prot","First: protagonist, protocol, prototype, protozoan",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (138,"Pseudo, Psed","False: pseudepigrapha, pseudoclassic, pseudomorph, pseudonym, pseudopod, pseduoscientific",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (139,"Pug, Pun","Hit, Prick: expunge, impugn, poignant, pugilist, pugnacious, punch punctual, punctuate, pungent repugnant",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (140,"Pyr","Fire: pyre, pyromania, pyrometer, pyrosis, pyrotechnic",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (141,"Qua, Quar, Quat","Four: quadrant quadrille, quadrinomial, quadruple, quadruplets, quart, quarter, quaternary",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (142,"Quie, Quit","Quiet, Test: acquiesce, acquit, coy, disuiet, quiescent, quiet, quietude, quietus, quit, reguiem, requital, tranquil",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (143,"Quint, Quin","Five: quincunx, quinquennial, quintessence, quintile, quintillion, quintuple",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (144,"Radi, Raci, Rami","Root, Branch: deracinate, eradicate, radical, radish, ramification, ramiform, ramify",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (145,"Re","Back, Again: recline, refer, regain, remain, reorganize, repent, request",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (146,"Rect","Straight, Right: correct, direct, erect, rectangle, rectify, rectilinear, rectitude, rector",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (147,"Retro","Backword: retroactive, retroflex, retrograde, retrospective",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (148,"Rub, Rud","Red: rouge, rebella, rubicund, rubric, ruby, ruddy, russet",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (149,"Rud","Crude: euridite, rude, rudimentary, rudiments",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (150,"Sacer, Sacr, Sanc","Holy: onsecration, desecrate, execrate, sacerdotal, sacrament, sacred, sacrifince, sacrilige, sacristy, sacrosanct, saint, santify, sanctimonious, sanction, sanctity, sancturary, sanctum",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (151,"Sal","Salt: salary, saline",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (152,"Sag, Sap, Sav","Taste, Think: insipid, sagacious, sagacity, sage, sapid, sapient, savant, savor",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (153,"Salu, Salv","Halth, Save: safe, salubrious, salutary, salute, salvage, salvation, salve, savior",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (154,"San","Healthy: sane, sanitarium, sanitation, sanity",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (155,"Sang","Blood: consanguinity, sanguinary, sanguine",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (156,"Sat","Enough: asset, dissatisfied, insatiable, sate, satiate, satisfy, saturate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (157,"Scrib, Scriv, Scr","Write: Ascribe, circumscription, conscript, describe, indescribable, inscription, posticript, prescribe, proscribe, scribble, scribe, script, scripture, scrivener, subscribe, transcription",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (158,"Se","Down, out, away, Apart: secede, seclude, secrete, secrete, secure, sedition, seduce, segregate, select, separate.",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (159,"Sed, Sid","Sit: assiduous, dissident, insidious, preside, reside, residue, seance, sedate, sedative, sedentary, sediment, sedulous, session, siege, subside, supersede",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (160,"Sem","Seed, Sow: disseminate, semen, seminal, seminar, seminary",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (161,"Semi","Half: semicircle, semicolon, semiconscious, semifluid",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (162,"Sen","Old: senate, senescent, senile, seniour, sire",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (163,"Sequ, Secu, Sue, ","Follow: consecutive, consequent, execute, exutive, non sequitur, obsequious, obsequy, persecute, prosecution, pursue, sequal,sequence, subsequent, sue, suitable, suite, suitor",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (164,"Sinu, Sin","Bend, Fold: consine, insuinuate, sine, sinuous, sinus",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (165,"Sol","Sun: parasol, solar, solarium, solstice",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (166,"Sol","Alone: desolate, isolate, sole, soliloquize, solipsism, solitude, solo",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (167,"Somn","Sleep: insomnia, somnambulist, somniferous, somniloquist, somnolent",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (168,"Soph","Wisom: philospher, sophism, sophist, sophistry, sophomore",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (169,"Spec, Spic","Look, See: aspeect, auspicious, circumspect, conspicious, despicable, expect, inspect, introspection, perspective, persicacious, perspicauous, prospectus, respectable, restrospect, specimen, spectacle, spectator, specter, spectrum, suspect, suspicious",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (170,"Spir","Breath: apire, conspire, expire, inspire, perspire, respirator, spirity, spiritual, sprightly, sprite, suspire, transpire",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (171,"Strict, String","Tight: astringency, constrain, constrict, district, resstriction, strain, strait, strangle, strict, stringent",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (172,"Sub","Under: subdivide, subdue, subjugate, subjunctive, sublunary, submarine, submerge, subdordinate, subpoena, subscribe, subside, substitude, subterfuge, subterranean, suburb",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (173,"Summ","Highest: consummate, sum, summary, summit",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (174,"Super, Sur","Above: insuperable, superabound, superannuated, superb, supercharge, supercilious, superficial, superflous, superior, surpass, surrealism, survey",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (175,"Surg, Sourc, Surr","Rise: insurgent, insurrection, resource, resurge, resurrection, source, surge",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (176,"Sym, Syn","Together: symbiosis, symmetry, sympathy, symposium, synonym, synthesis",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (177,"Tacit","Silent: reticent, tacit, taciturn",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (178,"Tact, Tag, Tam, T","Touch: contact, contagious, contamination, contiguous, contangent, intact, intangible, integral, tact, tactile, tangent, tangential",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (179,"Test","bear witness: attest, contest, detest, intestate, protest, testament, testify, testimonial",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (180,"Therm","Heat: diathermy, thermal, thermesthesia, thermometer, thermonuclear, thermophilic, thermos, thermoststat",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (181,"Tim","Fear: intimidate, timid, timidity, timorous",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (182,"Topr","Stiff, Numb: torpedo, torpid, torpor",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (183,"Torq, Tort, Tor","Twist: contort, distort, extor, retor, torch, torment, torque, torsion, tort, tortuous, torture",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (184,"Tox","Poison: antitoxin, intoxication, toxemia, toxis, tocicology, toxin",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (185,"Trans","Across Beyond: intransigent, transcend, transcontinental, transcribe, transient, trasnmit, transpire, transport",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (186,"Ult","Last, Beyond: penultimate, ulterior, ultimate, ultimatum, ultramarine, ultramontane, ultraviolet",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (187,"Umbr","Shadow: adumbrate, penumbra, somber, umber, umbrage, umbrella",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (188,"Un","Not: unaccustomed, unruly, unseen, untold, unusual",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (189,"Und","Wave: abound, abdundance, unundate, redundant, undulant, undulate",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (190,"Uni, Un","One: reunion, unanimous, unicord, uniform, union, unison, unit, unite, unity, universe",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (191,"Urb","City: exurbanite, suburban, urban, urbanity, urbanization",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (192,"Val, Vail","Strength, Use, Worth: ambivalent, avail, convalescent, countervailing, equivalent, evaluate, invalid, prevalent, valediction, valiant, valid, valor, value",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (193,"Ver","True: aver, veracious, verdict, verify, verily, verisimilitude, verity, verty",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (194,"Verb","Word: adverb, proverb, verb, verbal, verbalize, verbatime, verboze, verbiage",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (195,"Verd","Green: verdant, verdigris, verdure",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (196,"Vil","Base, Mean: revile, vile, vilify, vilification",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (197,"Vit, Viv","Life: convivial, revival, revive, survive, vital, vitality, vivacious, vivid, viviparous, vivisection",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (198,"Voc, Vou","Call, Word: advocacy, advocate, avow, convocation, convoke, equivoval, evoke, invocation, invoke, provoke, revoke, vocabulary, vocal, vocation",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (199,"Vol","Fly: volant, volatile, volley",6);
INSERT INTO cards (card_order, question, answer, deck_id) VALUES (200,"Volu, Volv","Roll, Tur: circumvolve, convolution, devolve, evolve, involution, revolt, revolve, voluble, colume, vouminous, volute.",6);
