INSERT INTO cards (question, answer, deck_id) VALUES ("Abate","verb - become less in amount or intensity; make less active or intense",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Aberrant","adj - markedly different from an accepted norm; noun one whose behavior departs substantially from the norm of a group",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Abeyance","noun - temporary cessation or suspension",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Abjure","verb - formally reject or disavow a formerly held belief,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ablution","noun - the ritual washing of a priest's hands or of sacred vessels",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Abrogate","verb - revoke formally",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Abscond","verb - run away; usually includes taking something or somebody along",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Abstemious","adj - sparing in consumption of especially food and drink; marked by temperance in indulgence",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Abstruse","adj - difficult to penetrate; incomprehensible to one of ordinary understanding or knowledge",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Accretion","noun -  the process of growth or increase,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Acerbic","adj - harsh or corrosive in tone; sour or bitter in taste",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Acquiesce","verb - to agree or express agreement",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Acrid","adj - harsh or corrosive in tone; strong and sharp; having an irritatingly strong and unpleasant taste or smell",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Adjoin","verb - attach or add; be in direct physical contact with; make contact; lie adjacent to another or share a boundary",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Admonish","verb - take to task; admonish or counsel in terms of someone's behavior; warn strongly; put on guard",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Adulterate","adj - mixed with impurities; verb corrupt,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Advocate","noun - a person who pleads for a cause or propounds an idea; a lawyer who pleads cases in court; verb speak,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Aesthetic","adj - concerned with beauty or the appreciation of beauty",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Affable","adj - diffusing warmth and friendliness",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Aggrandize","verb - add details to",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Alacrity","noun - liveliness and eagerness",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Alleviate","verb - provide physical relief,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Amalgamate","adj - joined together into a whole; verb to bring or combine together or with something else",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ambiguous","adj - having more than one possible meaning;",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ambivalence","noun - mixed feelings or emotions",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ambrosial","adj - worthy of the gods; extremely pleasing to the taste; sweet and fragrant",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ameliorate","verb - get better; to make better",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Anachronism","noun - an artifact that belongs to another time; a person who seems to be displaced in time; who belongs to another age; something located at a time when it could not have existed or occurred",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Anomalous","adj - deviating from the general or common order or type",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Antediluvian","adj - so extremely old as seeming to belong to an earlier period; of or relating to the period before the biblical flood; ridiculously old-fashioned",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Antipathy","noun - the object of a feeling of intense aversion; something to be avoided; a feeling of intense dislike",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Apathy","noun - the trait of lacking enthusiasm for or interest in things generally; an absence of emotion or enthusiasm",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Apogee","noun - the highest point in the development of something; the climax or culmination of something",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Apostasy","noun - the act of abandoning a party or cause; the state of having rejected your religious beliefs or your political party or a cause (often in favor of opposing beliefs or causes)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Apotheosis","noun - the elevation of a person (as to the status of a god); model of excellence or perfection of a kind; one having no equal",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Appease","verb - make peace with; overcome or allay; cause to be more favorably inclined; gain the good will of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Apprise","verb - increase the value of; gain in value; make aware of; inform (somebody) of something",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Approbation","noun - official recognition or approval; official approval",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Arbitrate","verb - act between parties with a view to reconciling differences",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Arduous","adj - difficult to accomplish;  characterized by toilsome effort to the point of exhaustion",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Artless","adj - simple and natural; without cunning or deceit; characterized by an inability to mask your feelings",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ascetic","adj - practicing great self-denial; noun - someone who practices self denial as a spiritual discipline",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Asperity","noun - harshness of manner; something hard to endure",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Assiduous","adj - marked by care and persistent effort",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Assuage","verb - provide physical relief,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Attenuate","adj - reduced in strength; verb become weaker,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Audacious","adj - disposed to venture or take risks; unrestrained by convention or propriety; invulnerable to fear or intimidation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Augury","noun - an event that is experienced as indicating important things to come",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Auspicious","adj - auguring favorable circumstances and good luck",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Austere","adj - of a stern or strict bearing or demeanor; forbidding in aspect; severely simple; practicing great self-denial",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Aver","verb - to declare or affirm solemnly and formally as true; report or maintain",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Baleful","adj - threatening or foreshadowing evil or tragic developments; deadly or sinister",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Banal","adj - repeated too often; overfamiliar through overuse",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Barefaced","adj - unrestrained by convention or propriety; with no effort to conceal",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Belie","verb - represent falsely; be in contradiction with",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Bellicose","adj - having or showing a ready disposition to fight",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Belligerent","adj - engaged in war; characteristic of an enemy or one eager to fight; noun someone who fights (or is fighting)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Benevolent","adj - generous in providing aid to others; intending or showing kindness; generous in assistance to the poor; showing or motivated by sympathy and understanding and generosity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Benign","adj - pleasant and beneficial in nature or influence; kindness of disposition or manner; not dangerous to health; not recurrent or progressive (especially of a tumor)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Blandishment","noun - the act of urging by means of teasing or flattery; flattery intended to persuade",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Blithe","adj - carefree and happy and lighthearted; lacking or showing a lack of due concern",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Bolster","verb - support and strengthen; prop up",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Bombast","noun - pompous or pretentious talk or writing",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Bombastic","adj - ostentatiously lofty in style",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Boorish","adj - ill-mannered and coarse and contemptible in behavior or appearance",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Breach","noun - a failure to perform some promised act or obligation; an opening (especially a gap in a dike or fortification)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Broach","noun - a decorative pin worn by women; verb bring up a topic for discussion",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Burgeon","verb - grow and flourish",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Burnish","noun - the property of being smooth and shiny; verb polish and make shiny",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Buttress","noun - a support usually of stone or brick; supports the wall of a building; verb make stronger or defensible; reinforce with a buttress",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cadge","verb - obtain or seek to obtain by cadging or wheedling; ask for and get free; be a parasite",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cajole","verb - influence or urge by gentle urging,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Capitulate","verb - surrender under agreed conditions",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Caprice","noun - a sudden desire",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Capricious","adj - determined by chance or impulse or whim rather than by necessity or reason; changeable",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Castigate","verb - inflict severe punishment on; censure severely",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Castigation","noun - verbal punishment; a severe scolding",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Catalyst","noun - something that causes an important event to happen; (chemistry) a substance that initiates or accelerates a chemical reaction without itself being affected",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Caustic","adj - harsh or corrosive in tone; sarcastic in a scathing and bitter way; noun - any chemical substance that burns or destroys living tissue",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Censure","noun - harsh criticism or disapproval; the state of being excommunicated; verb rebuke formally",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Chary","adj - characterized by great cautious and wariness",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Chicanery","noun - the use of tricks to deceive someone (usually to extract money from them)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Coda","noun - the closing section of a musical composition; a concluding event,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cogent","adj - powerfully persuasive",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Commensurate","adj - corresponding in size or degree or extent",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Complaisance","noun - a disposition or tendency to yield to the will of others",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Complaisant","adj - showing a cheerful willingness to do favors for others",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Compunction","noun - a feeling of deep regret (usually for some misdeed)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Conciliatory","adj - intended or likely to overcome animosity or hostility; making or willing to make concessions",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Condone","verb - excuse,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Conflagration","noun - a very intense and uncontrolled fire",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Confluence","noun - a flowing together; a place where things merge or flow together (especially rivers); a coming together of people",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Confound","verb - mistake one thing for another; be confusing or perplexing to; cause to be unable to think clearly",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Congenital","adj - present at birth but not necessarily hereditary; acquired during fetal development",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Connoisseur","noun - an expert able to appreciate a field; especially in the fine arts",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Contentious","adj - involving or likely to cause controversy; inclined or showing an inclination to dispute or disagree,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Contiguous","adj - very close or connected in space or time; having a common boundary or edge; touching; connecting without a break; within a common boundary",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Contrite","adj - feeling regret for a fault or offence; feeling or expressing pain or sorrow for sins or offenses",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Conundrum","noun - a difficult problem",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Convoke","verb - call together",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Convoluted","adj - highly complex or intricate",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Corporal","adj - possessing or existing in bodily form; affecting or characteristic of the body as opposed to the mind or spirit; noun a noncommissioned officer in the army or airforce or marines",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Corporeal","adj - having material or physical form or substance; affecting or characteristic of the body as opposed to the mind or spirit",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Corroborate","verb - support with evidence or authority or make more certain or confirm; establish or strengthen as with new evidence or facts; give evidence for",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Craven","adj - lacking even the rudiments of courage; abjectly fearful; noun an abject coward",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Credulity","noun - tendency to believe readily",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Credulous","adj - gullible; disposed to believe on little evidence; showing a lack of judgment or experience",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Culpable","adj - deserving blame or censure as being wrong or evil or injurious",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Cursory","adj - hasty and without attention to detail; not thorough",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Daunt","verb - cause to lose courage; make (someone) feel intimidated or apprehensive",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dearth","noun - an insufficient quantity or number; an acute insufficiency",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Decorum","noun - propriety in manners and conduct",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Deference","noun - a courteous expression (by word or deed) of esteem or regard; courteous regard for people's feelings; a disposition or tendency to yield to the will of others",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Deferential","adj - showing deference; respectful",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Deign","verb - do something that one considers to be below one's dignity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Delineate","adj - represented accurately or precisely; verb describe in vivid detail; determine the essential quality of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Denigrate","verb - charge falsely or with malicious intent; attack the good name and reputation of someone; cause to seem less serious; play down",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Depict","verb - give a description of; show in,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Deprecate","verb - belittle; express strong disapproval of; deplore",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Deprecation","noun - the act of expressing disapproval (especially of yourself); a prayer to avert or remove some evil or disaster",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Depredation","noun - an act of plundering and pillaging and marauding; (usually plural) a destructive action",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Deride","verb - treat or speak of with contempt",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Derision","noun - the act of deriding or treating with contempt; contemptuous laughter",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Derivative","adj - originating from,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Descry","verb - catch sight of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Desiccate","adj - lacking vitality or spirit; lifeless; verb lose water or moisture; remove water from; preserve by removing all water and liquids from",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Desultory","adj - marked by lack of definite plan or regularity or purpose; jumping from one thing to another",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Diaphanous","adj - so thin as to transmit light; (esp. of fabric) light,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Diatribe","noun - thunderous verbal attack",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dichotomy","noun - being twofold; a classification into two opposed parts or subclasses",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Didactic","adj - instructive (especially excessively)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Diffidence","noun - lack of self-confidence",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Diffident","adj - lacking self-confidence; showing modest reserve",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Diffuse","adj - spread out; not concentrated in one place; lacking conciseness; (of light) transmitted from a broad light source or reflected; verb move outward; cause to become widely known; spread or diffuse through",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dilatory","adj - wasting time; inclined to waste time and lag behind; using cautious slow strategy to wear down opposition; avoiding direct confrontation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dilettante","adj - showing frivolous or superficial interest; amateurish; noun an amateur who engages in an activity without serious intentions and who pretends to have knowledge",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dirge","noun - a song or hymn of mourning composed or performed as a memorial to a dead person",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Disabuse","verb - free somebody (from an erroneous belief); persuade (someone) that an idea or belief is mistaken",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Discordant","adj - not in agreement or harmony; lacking in harmony",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Discredit","noun - the state of being held in low esteem; verb cause to be distrusted or disbelieved; damage the reputation of; reject as false; refuse to accept",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Discrete","adj - constituting a separate entity or part",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Disinterested","adj - unaffected by self-interest",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Disparage","verb - express a negative opinion of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Disparaging","adj - expressive of low opinion",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Disparate","adj - including markedly dissimilar elements; fundamentally different or distinct in quality or kind",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dispassionate","adj - unaffected by strong emotion or prejudice",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dissemble","verb - behave unnaturally or affectedly; hide under a false appearance; make believe with the intent to deceive",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Disseminate","verb - cause to become widely known",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dissolution","noun - the termination or disintegration of a relationship (between persons or nations); separation into component parts; the termination of a meeting",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dissonance","noun - disagreeable sounds; the auditory experience of sound that lacks musical quality; a conflict of people's opinions or actions or characters",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Distend","verb - swell from or as if from internal pressure; cause to expand as it by internal pressure; become wider",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dogged","adj - stubbornly unyielding",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dogmatic","adj - characterized by assertion of unproved or unprovable principles; relating to or involving dogma; of or pertaining to or characteristic of a doctrine or code of beliefs accepted as authoritative",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dormant","adj - inactive but capable of becoming active;",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Dupe","noun - a person who is tricked or swindled; verb fool or hoax",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Duplicity","noun - acting in bad faith; deception by pretending to entertain one set of intentions while acting under the influence of another; a fraudulent or duplicitous representation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ebullient","adj - joyously unrestrained",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Eclectic","adj - selecting what seems best of various styles or ideas; noun someone who selects according to the eclectic method",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Efficacy","noun - capacity or power to produce a desired effect",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Effluent","adj - that is flowing outward; noun water mixed with waste matter; liquid waste or sewage discharged into a river or the sea",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Effrontery","noun - audacious (even arrogant) behavior that you have no right to",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Egress","noun - the act of coming (or going) out; becoming apparent; verb - go out of or leave a place",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Elegy","noun - a mournful poem; a lament for the dead",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Elicit","verb - derive by reason; deduce (a principle) or construe (a meaning); call forth (emotions,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Embellish","verb - make more beautiful; add details to; make more attractive by adding ornament,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Emollient","adj - having a softening or soothing effect especially to the skin; noun - a preparation that softens the skin",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Empirical","adj - derived from experiment and observation rather than theory; relying on medical quackery",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Emulate","verb - compete with successfully; approach or reach equality with; strive to equal or match,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Encomium","noun - a formal expression of praise",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Endemic","adj - native to or confined to a certain region; originating where it is found",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Enervate","verb - weaken mentally or morally; disturb the composure of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Engender","verb - call forth; make children",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Enigma","noun - something that baffles understanding and cannot be explained; a difficult problem",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ephemeral","adj - lasting a very short time; noun anything short-lived,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Epithet","noun - descriptive word or phrase; a defamatory or abusive word or phrase",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Equanimity","noun - steadiness of mind under stress",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Equivocal","adj - open to two or more interpretations; or of uncertain nature or significance; open to question",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Equivocate","verb - be deliberately ambiguous or unclear in order to mislead or withhold information",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Erratic","adj - liable to sudden unpredictable change; likely to perform unpredictably; having no fixed course",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Erudite","adj - having or showing profound knowledge",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Eschew","verb - avoid and stay away from deliberately; stay clear of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Esoteric","adj - confined to and understandable by only an enlightened inner circle",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Estimable","adj - deserving of respect or high regard; deserving of esteem and respect; may be computed or estimated",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Eulogy","noun - a formal expression of praise for someone who has died recently; a formal expression of praise",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Euphony","noun - any agreeable (pleasing and harmonious) sounds",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Exacerbate","verb - exasperate or irritate; make worse",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Exculpate","verb - pronounce not guilty of criminal charges",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Execrable","adj - deserving a curse; unequivocally detestable; of very poor quality or condition",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Exigency","noun - a pressing or urgent situation; a sudden unforeseen crisis (usually involving danger) that requires immediate action",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Exigent","adj - requiring precise accuracy; demanding attention",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Exorbitant","adj - greatly exceeding bounds of reason or moderation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Expatiate","verb - add details,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Explicit","adj - precisely and clearly expressed or readily observable; leaving nothing to implication; in accordance with fact or the primary meaning of a term",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Extant","adj - still in existence; not extinct or destroyed or lost",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Extirpate","verb - surgically remove (an organ); destroy completely,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Facetious","adj - cleverly amusing in tone",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fallacious","adj - based on an incorrect or misleading notion or information; containing or based on a fallacy; intended to deceive",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fathom","noun -  a linear unit of measurement (equal to 6 feet) for water depth; verb - come to understand; measure the depth (of water)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fatuous","adj - devoid of intelligence",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fawn","noun - young deer; a color or pigment varying around a light grey-brown color; verb - try to gain favor by cringing or flattering; give a servile display of exaggerated flattery or affection",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Feign","verb - make believe with the intent to deceive; make a pretence of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Felicitous","adj - exhibiting an agreeably appropriate manner or style; marked by good fortune",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fervent","adj - extremely hot; characterized by intense emotion",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fervid","adj - extremely hot; characterized by intense emotion",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fervor","noun - feelings of great warmth and intensity; the state of being emotionally aroused and worked up",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Flag","noun - emblem usually consisting of a rectangular piece of cloth of distinctive design; stratified stone that splits into pieces suitable as paving stones; verb - (of a person) become tired,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fledgling","adj - young and inexperienced; (of a young bird) having acquired its flight feathers; noun young bird that has just fledged or become capable of flying; any new participant in some activity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Florid","adj - inclined to a healthy reddish color often associated with outdoor life; elaborately or excessively ornamented",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Flout","verb - treat with contemptuous disregard; laugh at with contempt and derision",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Foment","verb - bathe with warm water or medicated lotions; try to stir up public opinion",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Forestall","verb - keep from happening or arising; make impossible; act in advance of; deal with ahead of time",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fractious","adj - unpredictably difficult in operation; likely to be troublesome; stubbornly resistant to authority or control; easily irritated or annoyed",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Fusillade","noun - rapid simultaneous discharge of firearms; verb attack with fusillade",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Gainsay","verb - take exception to",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Garrulous","adj - full of trivial conversation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Germane","adj - having close kinship and appropriateness",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Goad","noun -  a spiked stick used for driving cattle; verb - provoke or annoy (someone) so as to stimulate some action or reaction",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Gossamer","adj - characterized by unusual lightness and delicacy; so thin as to transmit light; noun a gauze fabric with an extremely fine texture",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Gouge","noun - an impression in a surface (as made by a blow); verb force with the thumb; make a groove in; obtain by coercion or intimidation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Grandiloquent","adj - puffed up with vanity; lofty in style",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Gregarious","adj - instinctively or temperamentally seeking and enjoying the company of others; (of animals) tending to form a group with others of the same species; (of plants) growing in groups that are close together",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Guile","noun - the use of tricks to deceive someone (usually to extract money from them); the quality of being crafty; shrewdness as demonstrated by being skilled in deception",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Guileless","adj - free from guile; free of deceit; innocent and without deception",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Gullible","adj - easily tricked because of being too trusting; naive and easily deceived or tricked",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Halcyon","adj - idyllically calm and peaceful; suggesting happy tranquillity; marked by peace and prosperity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Hapless","adj - deserving or inciting pity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Harangue","noun - a loud bombastic declamation expressed with strong emotion; verb deliver a harangue to; address forcefully",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Headlong","adj - with the head foremost; excessively quick; adv",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Heterodox","adj - characterized by departure from accepted beliefs or standards",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Heterogeneous","adj - consisting of elements that are not of the same kind or nature; originating outside the body",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Homogenous","adj - all of the same or similar kind or nature",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Hyperbole","noun - extravagant exaggeration",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Iconoclast","noun - someone who attacks cherished ideas or traditional institutions; a destroyer of images used in religious worship",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ignominious","adj - (used of conduct or character) deserving or bringing disgrace or shame",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Immutable","adj - not subject or susceptible to change or variation in form or quality or nature",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Impair","verb - make worse or less effective; make imperfect",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Impassive","adj - having or revealing little emotion or sensibility; not easily aroused or excited; deliberately impassive in manner",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Impecunious","adj - not having enough money to pay for necessities",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Impede","verb - be a hindrance or obstacle to; block passage through",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Imperious","adj - able to deal authoritatively with affairs",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Imperturbable","adj - not easily perturbed or excited or upset; marked by extreme calm and composure",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Impervious","adj - not admitting of passage or capable of being affected",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Impetuous","adj - marked by violent force; characterized by undue haste and lack of thought or deliberation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Implacable","adj - incapable of being placated",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Implication","noun - an accusation that brings into intimate and usually incriminating connection; a meaning that is not expressly stated but can be inferred",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Implicit","adj - being without doubt or reserve; implied though not directly expressed; inherent in the nature of something",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Imply","verb - express or state indirectly; suggest as a logically necessary consequence; suggest that someone is guilty",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Importune","verb - beg persistently and urgently",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Improvidence","noun - a lack of prudence and care by someone in the management of resources",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Impugn","verb - attack as false or wrong",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Inchoate","adj - only partly in existence; imperfectly formed",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Incipient","adj - only partly in existence; imperfectly formed",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Incorrigible","adj - impervious to correction by punishment",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Incursion","noun - the act of entering some territory or domain (often in large numbers); the mistake of incurring liability or blame; an attack that penetrates into enemy territory",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Indelible","adj - cannot be removed,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Indigence","noun - a state of extreme poverty or destitution",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Indolence","noun - inactivity resulting from a dislike of work",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Indolent","adj - causing little or no pain; wanting to avoid activity or exertion; lazy.",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ineffable","adj - too sacred to be uttered; defying expression or description",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Inert","adj - slow and apathetic; unable to move or resist motion; having only a limited ability to react chemically; chemically inactive",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Infer","verb - believe to be the case; guess correctly; solve by guessing; reason by deduction; establish by deduction; conclude by reasoning; in logic; draw from specific cases for more general cases",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ingenious","adj - showing inventiveness and skill; skillful (or showing skill) in adapting means to ends; (used of persons or artifacts) marked by independence and creativity in thought or action",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ingenuous","adj - characterized by an inability to mask your feelings; not devious; lacking in sophistication or worldliness",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Inherent","adj - in the nature of something though not readily apparent; existing as an essential constituent or characteristic",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Inhibit","verb - limit the range or extent of; to put down by force or authority",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Inimical","adj - not friendly",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Innocuous","adj - not injurious to physical or mental health; not causing disapproval; lacking intent or capacity to injure; unlikely to harm or disturb anyone",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Insensible","adj - unresponsive to stimulation; incapable of physical sensation; unaware of or indifferent to; barely able to be perceived",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Insinuate","verb - introduce or insert (oneself) in a subtle manner; give to understand",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Insipid","adj - not pleasing to the sense of taste; lacking interest or significance; lacking significance or impact; lacking taste or flavor or tang",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Insular","adj - narrowly restricted in outlook or scope; suggestive of the isolated life of an island; relating to or characteristic of or situated on an island",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Intractable","adj - not tractable; difficult to manage or mold",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Intransigence","noun - the trait of being intransigent; stubbornly refusing to compromise",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Intransigent","adj - impervious to pleas,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Intrepid","adj - invulnerable to fear or intimidation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Inundate","verb - fill or cover completely,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Inured","adj - made tough by habitual exposure",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Invective","noun - abusive or venomous language used to express blame or censure or bitter deep-seated ill will",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Inveterate","adj - having a habit of long standing",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Irascible","adj - characterized by anger; quickly aroused to anger",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lachrymose","adj - showing sorrow",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Laconic","adj - brief and to the point; effectively cut short",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lassitude","noun - weakness characterized by a lack of vitality or energy; a feeling of lack of interest or energy; a state of comatose torpor (as found in sleeping sickness)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Latent","adj - not presently active; potentially existing but not presently evident or realized",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Laud","verb - praise,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Laudable","adj - worthy of high praise",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lethargic","adj - deficient in alertness or activity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Levee","noun - an embankment that is built in order to prevent a river from overflowing; a pier that provides a landing place on a river;",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Leviathan","noun - monstrous sea creature symbolizing evil in the Old Testament; the largest or most massive thing of its kind",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Levity","noun - a manner lacking seriousness; feeling an inappropriate lack of seriousness",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Loquacious","adj - full of trivial conversation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lucid","adj - having a clear mind; easily understandable; transmitting light; able to be seen through with clarity; capable of thinking and expressing yourself in a clear and consistent manner",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Lugubrious","adj - excessively mournful",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Luminous","adj - softly bright or radiant",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Magnanimity","noun - liberality in bestowing gifts; extremely liberal and generous of spirit",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Magnate","noun - a very wealthy or powerful businessman",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Maladroit","adj - not adroit",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Malevolent","adj - wishing or appearing to wish evil to others; arising from intense ill will or hatred; having or exerting a malignant influence",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Malign","adj - evil or harmful in nature or influence; having or exerting a malignant influence; verb speak unfavorably about",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Malinger","verb - exaggerate or feign illness in order to escape duty or work.",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Malleable","adj - capable of being shaped or bent or drawn out; easily influenced",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Maverick","adj - independent in behavior or thought; noun - someone who exhibits great independence in thought and action",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mendacious","adj - intentionally untrue; given to lying",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Meretricious","adj - like or relating to a prostitute; based on pretense; deceptively pleasing; tastelessly showy",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Meticulous","adj - marked by extreme care in treatment of details; marked by precise accordance with details",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mettlesome","adj - having a proud and unbroken spirit; willing to face danger",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Minatory","adj - threatening or foreshadowing evil or tragic developments",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Misanthrope","noun - someone who dislikes people in general",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Misnomer","noun - an incorrect or unsuitable name",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Misogynist","noun - a misanthrope who dislikes women in particular",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mitigate","verb - make less severe or harsh; lessen or to try to lessen the seriousness or extent of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mollify","verb - make less rigid or softer; make more temperate,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Morose","adj - showing a brooding ill humor",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Mundane","adj - belonging to this earth or world; not ideal or heavenly; concerned with the world or worldly matters; found in the ordinary course of events",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nadir","noun - an extreme state of adversity; the lowest point of anything",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nascent","adj - being born or beginning",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nefarious","adj - extremely wicked",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Neophyte","noun - a plant that is found in an area where it had not been recorded previously; any new participant in some activity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Noisome","adj - offensively malodorous; causing or able to cause nausea",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Nostrum","noun - patent medicine whose efficacy is questionable; hypothetical remedy for all ills or diseases; once sought by the alchemists",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Noxious","adj - injurious to physical or mental health",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Obdurate","adj - showing unfeeling resistance to tender feelings; stubbornly persistent in wrongdoing",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Obfuscate","verb - make obscure or unclear",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Oblique","adj. - slanting or inclined in direction or course or position--neither parallel nor perpendicular nor right-angled; indirect in departing from the accepted or proper way; misleading;",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Obsequious","adj - attentive in an ingratiating or servile manner; attempting to win favor from influential people by flattery",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Obstreperous","adj - boisterously and noisily aggressive; noisily and stubbornly defiant",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Obtuse","adj - lacking in insight or discernment; of an angle; between 90 and 180 degrees; slow to learn or understand; lacking intellectual acuity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Obviate","verb - do away with; prevent the occurrence of; prevent from happening",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Occlude","verb - block passage through",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Odious","adj - unequivocally detestable",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Officious","adj - intrusive in a meddling or offensive manner",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Onerous","adj - not easily borne; wearing",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Opaque","adj - not clear; not transmitting or reflecting light or radiant energy; not clearly understood or expressed",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Opprobrium","noun - a state of extreme dishonor; state of disgrace resulting from public abuse",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ossified","adj - changed into bone; hardened by deposits of mineral matter; set in a rigidly conventional pattern of behavior,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ostentatious","adj - intended to attract notice and impress others; of a display that is tawdry or vulgar",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Panegyric","adj - formally expressing praise; noun a formal expression of praise",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Panoply","noun - a complete and impressive array",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Paragon","noun - an ideal instance; a perfect embodiment of a concept; model of excellence or perfection of a kind; one having no equal",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pariah","noun - a person who is rejected (from society or home)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Parsimonious","adj - excessively unwilling to spend",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Partisan","adj - devoted to a cause or party; adhering or confined to a particular sect or denomination or party; noun- an ardent and enthusiastic supporter of some person or activity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Paucity","noun - an insufficient quantity or number",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Peccadillo","noun - a petty misdeed; a small,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pedantic","adj - marked by a narrow focus on or display of learning especially its trivial aspects",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pedestrian","adj - lacking wit or imagination; noun a person who travels by foot",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Penchant","noun - a strong liking",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Penury","noun - a state of extreme poverty or destitution",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Peremptory","adj - putting an end to all debate or action; not allowing contradiction or refusal; offensively self-assured or given to exercising usually unwarranted power",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Perennial","adj - recurring again and again; lasting three seasons or more; lasting an indefinitely long time; suggesting self-renewal; noun a plant lasting for three seasons or more",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Perfidious","adj - tending to betray; especially having a treacherous character as attributed to the Carthaginians by the Romans",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Perfidy","noun - betrayal of a trust; an act of deliberate betrayal",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Perfunctory","adj - hasty and without attention to detail; not thorough; as a formality only",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Peripatetic","adj - traveling especially on foot; of or relating to Aristotle or his philosophy; noun a person who walks from place to place; a follower of Aristotle or an adherent of Aristotelianism",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pernicious","adj - working or spreading in a hidden and usually injurious way; exceedingly harmful",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Perspicacious","adj - acutely insightful and wise; mentally acute or penetratingly discerning",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pertinacious","adj - stubbornly unyielding",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Petulant","adj - easily irritated or annoyed",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Philanthropy","noun - voluntary promotion of human welfare",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Phlegmatic","adj - showing little emotion",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pious","adj - having or showing or expressing reverence for a deity; devoutly religious",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pique","noun - tightly woven fabric with raised cords; a sudden outburst of anger; verb cause to feel resentment or indignation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Placate","verb - cause to be more favorably inclined; gain the good will of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Plastic","adj - made of plastic; capable of being influenced or formed; forming or capable of forming or molding or fashioning; offering scope for creativity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Platitude","noun - a trite or obvious remark",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Plethora","noun - extreme excess",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Plumb","adj - exactly vertical; adv - exactly",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Plummet","noun - the metal bob of a plumb line; verb drop sharply",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Poignant","adj - keenly distressing to the mind or feelings; arousing affect",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ponderous","adj - having great mass and weight and unwieldiness; labored and dull; slow and laborious because of weight",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pragmatic","adj - concerned with practical matters; guided by practical experience and observation rather than theory",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Precarious","adj - affording no ease or reassurance; not secure; beset with difficulties; dangerously insecure; fraught with danger",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Precept","noun - a doctrine that is taught; rule of personal conduct",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Precipice","noun - a very steep cliff",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Precipitate","adj - done with very great haste and without due deliberation; verb - separate as a fine suspension of solid particles; bring about abruptly; fall vertically,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Preclude","verb - make impossible,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Precocious","adj - appearing or developing early; characterized by or characteristic of exceptionally early development or maturity (especially in mental aptitude)",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Precursor","noun - a person who goes before or announces the coming of another; an indication of the approach of something or someone",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Predilection","noun - a predisposition in favor of something; a strong liking",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Presumptuous","adj - excessively forward",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Prevaricate","verb - be deliberately ambiguous or unclear in order to mislead or withhold information",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pristine","adj - immaculately clean and unused; completely free from dirt or contamination",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Probity","noun - complete and confirmed integrity; having strong moral principles",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Proclivity","noun - a natural inclination",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Prodigal","adj - marked by rash extravagance; very generous; recklessly wasteful; noun a recklessly extravagant consumer",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Prodigious","adj - so great in size or force or extent as to elicit awe; far beyond what is usual in magnitude or degree; of momentous or ominous significance",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Proliferate","verb - cause to grow or increase rapidly; grow rapidly",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Propensity","noun - a disposition to behave in a certain way; a natural inclination; an inclination to do something",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Propitiate","verb - make peace with",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Propriety","noun - correct or appropriate behavior",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Prosaic","adj - not challenging; dull and lacking excitement; lacking wit or imagination; not fanciful or imaginative",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Proscribe","verb - command against",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Provident","adj - providing carefully for the future; careful in regard to your own interests",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Prudence","noun - discretion in practical affairs; knowing how to avoid embarrassment or distress",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Puerile","adj - of or characteristic of a child; displaying or suggesting a lack of maturity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pugnacious","adj - ready and able to resort to force or violence; tough and callous by virtue of experience",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pulchritudinous","adj - used of persons only; having great physical beauty",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Punctilious","adj - marked by precise accordance with details",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pungent","adj - strong and sharp; ""the pungent taste of radishes""; capable of wounding",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Pusillanimous","adj - lacking in courage and manly strength and resolution; contemptibly fearful",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Querulous","adj - habitually complaining",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Quibble","verb - argue over petty things; evade the truth of a point or question by raising irrelevant objections",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Quiescence","noun - quiet and inactive restfulness; a state of quiet (but possibly temporary) inaction",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Quiescent","adj - causing no symptoms; being quiet or still or inactive; not active or activated; marked by a state of tranquil repose",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Quotidian","adj - found in the ordinary course of events",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Rarefy","verb - make more subtle or refined; lessen the density or solidity of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Recalcitrant","adj - marked by stubborn resistance to authority; stubbornly resistant to authority or control",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Recant","verb - formally reject or disavow a formerly held belief,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Recluse","adj - withdrawn from society; seeking solitude; noun one who lives in solitude",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Recondite","adj - difficult to penetrate; incomprehensible to one of ordinary understanding or knowledge",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Recumbent","adj - lying down; in a position of comfort or rest",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Refractory","adj - not responding to treatment; stubbornly resistant to authority or control",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Refute","verb - prove to be false or incorrect; overthrow by argument,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Regale","verb - provide with choice or abundant food or drink",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Relegate","verb - assign to a class or kind; refer to another person for decision or judgment; assign to a lower position; reduce in rank; expel,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Remonstrate","verb - argue in protest or opposition; present and urge reasons in opposition; censure severely or angrily",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Repine","verb - express discontent",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Reprobate","adj - marked by immorality; deviating from what is considered right or proper or good; noun a person without moral scruples",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Reproof","noun - an act or expression of criticism and censure; verb censure severely or angrily",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Repudiate","verb - refuse to acknowledge,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Rescind","verb - annul by recalling or rescinding",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Reticent","adj - reluctant to draw attention to yourself; temperamentally disinclined to talk; cool and formal in manner",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Reverent","adj - feeling or showing profound respect or veneration; showing great reverence for god",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sagacious","adj - skillful in statecraft or management; acutely insightful and wise",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Salacious","adj - suggestive of or tending to moral looseness; characterized by lust",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Salient","adj -  having a quality that thrusts itself into attention; prominent",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Salubrious","adj - favorable to health of mind or body; promoting health; healthful",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Salutary","adj - tending to promote physical well-being; beneficial to health",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sanction","noun - a mechanism of social control for enforcing a society's standards; formal and explicit approval; official permission or approval; verb give religious sanction to,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sanguine","adj - confidently optimistic and cheerful; inclined to a healthy reddish color often associated with outdoor life; noun a blood-red color",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sate","verb - fill to satisfaction",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Satiate","adj - supplied (especially fed) to satisfaction; verb fill to satisfaction; overeat or eat immodestly",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Saturnine","adj - bitter or scornful; showing a brooding ill humor",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Savant","noun - someone who has been admitted to membership in a scholarly field",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Savor","noun - verb taste appreciatively; give taste to; derive or receive pleasure from; take pleasure in",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sedulous","adj - marked by care and persistent effort",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Shard","noun - a broken piece of a brittle artifact",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Solicitous","adj - showing hovering attentiveness; full of anxiety and concern",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Soporific","adj - sleep inducing; inducing mental lethargy; noun a drug that induces sleep",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Specious","adj - plausible but false; based on pretense; deceptively pleasing",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sporadic","adj - recurring in scattered and irregular or unpredictable instances",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Spurious","adj - intended to deceive; born out of wedlock; plausible but false",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Squalid","adj - foul and run-down and repulsive; morally degraded",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Stanch","verb - stop the flow of a liquid",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Stigma","noun - a skin lesion that is a diagnostic sign of some disease; a mark of disgrace associated with a particular circumstance,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Stint","noun - limitation of supply or effort; a person's fixed or allotted period of work; an unbroken period of time during which you do something",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Stipulate","verb - demand or specify (a requirement),5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Stolid","adj - having or revealing little emotion or sensibility; not easily aroused or excited",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Strut","noun - a proud stiff pompous gait; brace consisting of a bar or rod used to resist longitudinal compression; verb to walk with a lofty proud gait,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Subterfuge","noun - something intended to misrepresent the true nature of an activity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Supercilious","adj - expressive of contempt; having or showing arrogant superiority to and disdain of those one views as unworthy",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Superficial","adj - being or affecting or concerned with a surface; not deep or penetrating emotionally or intellectually; of little substance or significance; relating to a surface; involving a surface only",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Supersede","verb - take the place or move into the position of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Supine","adj - lying face upward; offering no resistance",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Supplicate","verb - ask humbly (for something); ask for humbly or earnestly,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Sycophant","noun - a person who tries to please someone in order to gain a personal advantage",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tacit","adj - indicated by necessary connotation though not expressed directly",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Taciturn","adj - habitually reserved and uncommunicative",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Temperate","adj - not extreme in behavior; (of weather or climate) free from extremes; mild; or characteristic of such weather or climate; not extreme",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tenacious","adj - sticking together; good at remembering; stubbornly unyielding",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tendentious","adj - having or marked by a strong tendency especially a controversial one",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tenuous","adj - very thin in gauge or diameter; having thin consistency; having little substance or significance",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Terse","adj - brief and to the point; effectively cut short",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Timorous","adj - timid by nature or revealing timidity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tirade","noun - a speech of violent denunciation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Torpid","adj - slow and apathetic; in a condition of biological rest or suspended animation",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Torpor","noun - a state of motor and mental inactivity with a partial suspension of sensibility; inactivity resulting from lethargy and lack of vigor or energy",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tortuous","adj - not straightforward; marked by repeated turns and bends; highly complex or intricate",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tractable","adj - easily managed (controlled or taught or molded); readily reacting to suggestions and influences",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Transient","adj - causing effects outside the mind; impermanent; lasting a very short time; noun - one who stays for only a short time",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Travesty","noun - a composition that imitates somebody's style in a humorous way; a comedy characterized by broad satire and improbable situations; verb make a travesty of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Truculence","noun - obstreperous and defiant aggressiveness",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Turpitude","noun - a corrupt or depraved or degenerate act or practice",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Tyro","noun - someone new to a field or activity",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Ubiquitous","adj - being present everywhere at once",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Umbrage","noun - a feeling of anger caused by being offended",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Untoward","adj - contrary to your interests or welfare; not in keeping with accepted standards of what is right or proper in polite society",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Upbraid","verb - express criticism towards",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vacillate","verb - move or sway in a rising and falling or wavelike pattern; be undecided about something; waver between conflicting positions or courses of action",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vacuous","adj - devoid of matter; void of expression; devoid of significance or point; devoid of intelligence",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Venal","adj - capable of being corrupted",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Venerate","verb - regard with feelings of respect and reverence; consider hallowed or exalted or be in awe of",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Veracious","adj - precisely accurate; habitually speaking the truth",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Veracity","noun - unwillingness to tell lies",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Verbose","adj - using or containing too many words",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Verisimilitude","noun - the appearance of truth; the quality of seeming to be true",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Veritable","adj - not counterfeit or copied; often used as intensifiers",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vex","verb - subject to prolonged examination,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vilify","verb - spread negative information about",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Viscous","adj - having the sticky properties of an adhesive; having a relatively high resistance to flow",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vitiate","verb - take away the legal force of or render ineffective; make imperfect; corrupt morally or by intemperance or sensuality",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vituperate","verb - spread negative information about",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Vociferous","adj - conspicuously and offensively loud; given to vehement outcry",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Volatile","adj - tending to vary often or widely; evaporating readily at normal temperatures and pressures; marked by erratic changeableness in affections or attachments",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Voracious","adj - devouring or craving food in great quantities; excessively greedy and grasping",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Waver","noun - the act of moving back and forth; the act of pausing uncertainly; verb sway to and fro; move hesitatingly,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Welter","noun - a confused multitude of things; verb be immersed in; toss,5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Whimsical","adj - determined by chance or impulse or whim rather than by necessity or reason",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Wretched","adj - characterized by physical misery; deserving or inciting pity; morally reprehensible; very unhappy; full of misery; of very poor quality or condition",5);
INSERT INTO cards (question, answer, deck_id) VALUES ("Zeal","noun - excessive fervor to do something or accomplish some end; prompt willingness; a feeling of strong eagerness (usually in favor of a person or cause)",5);
