SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `flashcards`.`my_decks` DROP FOREIGN KEY `user_id_md` ;

ALTER TABLE `flashcards`.`my_decks` 
  ADD CONSTRAINT `user_id_md`
  FOREIGN KEY (`user_id` )
  REFERENCES `flashcards`.`users` (`id` )
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE `flashcards`.`ratings` DROP FOREIGN KEY `user_id_r` ;

ALTER TABLE `flashcards`.`ratings` 
  ADD CONSTRAINT `user_id_r`
  FOREIGN KEY (`user_id` )
  REFERENCES `flashcards`.`users` (`id` )
  ON DELETE CASCADE
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
